<html>
<head>
</head>
<body>
    <div style="margin-left:15px;text-align:justify">

        These Terms of Use <strong>("Terms")</strong> were last updated on February 20, 2020 .<br><br>
        Yellow Alley’s mission is to improve lives through learning. We enable anyone anywhere to create and share educational courses and to enrol in these educational courses to learn (students). We consider our marketplace model the best way to offer valuable educational content to our users. We need rules to keep our platform and services safe for you, us and our student community. These Terms apply to all your activities on the Yellow Alley website, the Yellow Alley mobile applications, our TV applications, our APIs and other related services <strong>(“Services”)</strong>.<br><br>
        We provide details regarding our processing of personal data of our students in our Privacy Policy.<br><br>
        <strong>By using the Services, you agree to the terms of this Privacy Policy</strong>. You shouldn’t use the Services if you don’t agree with this Privacy Policy or any other agreement that governs your use of the Services.<br><br>
        By agreeing to these Terms, you agree to resolve disputes with Yellow Alley through binding arbitration (with very limited exceptions, not in court), and you waive certain rights to participate in class actions, as detailed in the Dispute Resolution section.

        <h4>1. Accounts</h4>
        You need an account for most activities on our platform. Keep your OTP safe, because you’re responsible for all activity associated with your account. If you suspect someone else is using your account, let us know by contacting us.<br><br>

        You need an account for most activities on our platform, including to purchase and enrol in a course. When setting up and maintaining your account, you must provide and continue to provide accurate and complete information, including a valid email address and phone number. You have complete responsibility for your account and everything that happens on your account, including for any harm or damage (to us or anyone else) caused by someone using your account without your permission. This means you need to be careful with your mobile number & OTP. You cannot transfer your account to someone else or use someone else’s account without our permission. If you contact us to request access to an account, we will not grant you such access unless you can provide us the login credential information for that account. In the event of the death of a user, the account of that user will be closed.<br><br>
        If you share your account login credential with someone else, you are responsible for what happens with your account and Yellow Alley can take strict actions with both the persons involved in the activity. You must notify us immediately upon learning that someone else may be using your account without your permission (or if you suspect any other breach of security) by contacting us. We may request some information from you to confirm that you are indeed the owner of your account.<br><br>
        Students must be at least 13 years of age to create an account on Yellow Alley and use the Services. If you are younger than the required age, you may not set up an account, but we encourage you to invite a parent or guardian to open an account and help you enrol in courses that are appropriate for you. If we discover that you have created an account and you are younger than the required age for consent to use online services we will terminate your account.
        <h4>2. Course Enrolment and Limited time Access</h4>

        When you enrol in a course, you get a license from us to view it via the Yellow Alley Services and no other use. Don’t try to transfer or resell courses in any way. We grant you a license, except when we must disable the course because of legal or policy reasons.<br><br>
        As a student, when you enrol in a course, whether it’s a free or paid course, you are getting from Yellow Alley a license to view the course via the Yellow Alley platform and Services, and Yellow Alley is the licensor of record. Courses are licensed, and not sold, to you. This license does not give you any right to resell the course in any manner (including by sharing account information with a purchaser or illegally downloading the course and sharing it on torrent sites).<br><br>
        In legal, more complete terms, Yellow Alley grants you (as a student) a limited, non-exclusive, non-transferable license to access and view the courses and associated content for which you have paid all required fees, solely for your personal, non- commercial, educational purposes through the Services, in accordance with these Terms and any conditions or restrictions associated with a particular courses or feature of our Services. All other uses are expressly prohibited. You may not reproduce, redistribute, transmit, assign, sell, broadcast, rent, lend, modify, adapt, edit, create derivative works of, sublicense, or otherwise transfer or use any course unless we give you explicit permission to do so in a written agreement signed by a Yellow Alley authorized representative. This also applies to content you can access via any of our APIs.<br><br>
        We generally give a limited period license to our students when they enrol in a course. However, we reserve the right to revoke any license to access and use courses at any point in time in the event where we decide or are obligated to disable access to a course due to legal or policy reasons, for example, if the course you enrolled in is the object of a copyright complaint, or if we determine its content violates our Trust & Safety Guidelines.
        <h4>3. Payments, Credits, and Refunds</h4>
        When you make a payment, you agree to use a valid payment method. Payment once made will not be refunded as Yellow Alley provides 5-days free trial with few free videos.
        <h4>3.1 Pricing</h4>
        The prices of courses on Yellow Alley are determined based on our Pricing and Promotions Policy. In some instances, the price of a course offered on the Yellow Alley website may not be exactly the same as the price offered on our mobile or TV applications, due to mobile platform providers’ pricing systems and their policies around implementing sales and promotions.<br><br>
        We regularly run promotions and sales for our courses and certain courses are only available at discounted prices for a set period of time. The price applicable to a course will be the price at the time you complete your purchase of the course (at checkout). Any price offered for a particular course may also be different when you are logged into your account from the price available to users who aren’t registered or logged in, because some of our promotions are available to new users only.<br><br>
        If you are logged into your account, the listed currency you see is based on your location when you created your account. If you are not logged into your account, the price currency is based on the country where you are located. We do not enable users to see pricing in other currencies.<br><br>
        If you are a student located in a country where use and sales tax, goods and services tax, or value added tax is applicable to consumer sales, we are responsible for collecting and remitting that tax to the proper tax authorities. In certain countries, the price you see may include such taxes.
        <h4>3.2 Payments</h4>
        You agree to pay the fees for courses that you purchase, and you authorize us to charge your debit or credit card or process other means of payment for those fees. Yellow Alley works with third party payment processing partners to offer you the most convenient payment methods in your country and to keep your payment information secure. Check out our Privacy Policy for more details.<br><br>
        When you make a purchase, you agree not to use an invalid or unauthorized payment method. If your payment method fails and you still get access to the course you are enrolling in, you agree to pay us the corresponding fees within thirty (30) days of notification from us. We reserve the right to disable access to any course for which we have not received adequate payments.
        <h4>3.3 Refunds and Credits</h4>
        Payment once made will not be refunded as Yellow Alley provides 5-days free trial with few free videos.<br>
        At our discretion, if we believe you are abusing our credit/refund policy, we reserve the right to ban your account and to restrict all future use of the Services. If we ban your account or disable your access to a course due to your violation of these Terms or our Trust & Safety Guidelines, you will not be eligible to receive any credit or refund.
        <h4>4. Content and Behaviour Rules</h4>
        You can only use Yellow Alley for lawful purposes. We can ban your account for repeated or major offenses. If you think someone is infringing your copyright on our platform, let us know.<br><br>
        You may not access or use the Services or create an account for unlawful purposes. Your use of the Services and behaviour on our platform must comply with applicable local or national laws or regulations of your country. You are solely responsible for the knowledge of and compliance with such laws and regulations that are applicable to you. You may not access our Services if you are from a territory which are banned for such <br><br>
        Yellow Alley complies with copyright laws. Yellow Alley has discretion in enforcing these Terms and our Trust & Safety Guidelines. We may terminate or suspend your permission to use our platform and Services or ban your account at any time, with or without notice, for any violation of these Terms like if you fail to pay any fees when due, upon the request of law enforcement or government agencies, for extended periods of inactivity, for unexpected technical issues or problems, or if we suspect that you engage in fraudulent or illegal activities. Upon any such termination we may delete your account and content, and we may prevent you from further access to the platforms and use of our Services. You agree that we will have no liability to you or any third party for termination of your account or blocking of your access to our platforms and services.
        <h4>5. Using Yellow Alley at Your Own Risk</h4>
        Anyone can create Yellow Alley account to educate themselves with the courses we provide.<br>
        Yellow Alley enables anyone anywhere to create account and learn educational courses. We do not guarantee in any manner the reliability, validity, accuracy or truthfulness of the courses. If you enrol a course, you rely on any information provided by the course at your own risk.<br><br>
        By using the Services, you may be exposed to content that you consider offensive, indecent, or objectionable. Yellow Alley has no responsibility to keep such content from you and no liability for your access or enrolment in any course, to the extent permissible under applicable law. This also applies to any courses relating to health, wellness and physical exercise. You acknowledge the inherent risks and dangers in the strenuous nature of these types of courses, and by enrolling in such courses, you choose to assume those risks voluntarily, including risk of illness, bodily injury, disability, or death. You assume full responsibility for the choices you make before, during and after your enrolment in a course.<br><br>
        We are not liable for disputes, claims, losses, injuries, or damage of any kind that might arise out of or relate to the conduct of students.<br><br>
        When you use our Services, you will find links to other websites that we don’t own or control. We are not responsible for the content or any other aspect of these third-party sites, including their collection of information about you. You should also read their terms and conditions and privacy policies.
        <h4>6. Yellow Alley’s Rights</h4>
        We own the Yellow Alley platform and Services, including the website, present or future apps and services, and things like our logos, API, code, and content created by us. You can’t tamper with those or use them without authorization.<br><br>
        All right, title and interest in and to the Yellow Alley platform and Services, including our website, our existing or future applications, our APIs, databases, and the content our employees or partners submit or provide through our Services (but excluding content provided by students) are and will remain the exclusive property of Yellow Alley and its licensors. Our platforms and services are protected by copyright, trademark, and other laws. Nothing gives you a right to use the Yellow Alley name or any of the Yellow Alley trademarks, logos, domain names, and other distinctive brand features. Any feedback, comments, or suggestions you may provide regarding Yellow Alley or the Services is entirely voluntary and we will be free to use such feedback, comments, or suggestions as we see fit and without any obligation to you.<br><br>
        You may not do any of the following while accessing or using the Yellow Alley platform and Services:<br><br>
        <ul>
            <li>
        Access, tamper with, or use non-public areas of the platform, Yellow Alley’s computer systems, or the technical delivery systems of Yellow Alley’s service providers.</li>
        <li>Disable, interfere with, or try to circumvent any of the features of the platforms related to security or probe, scan, or test the vulnerability of any of our systems.</li>
        <li>Copy, modify, create a derivative work of, reverse engineer, reverse assemble, or otherwise attempt to discover any source code of or content on the Yellow Alley platform or Services.</li>
        <li>Access or search or attempt to access or search our platform by any means (automated or otherwise) other than through our currently available search functionalities that are provided via our website, mobile apps, or API (and only pursuant to those API terms and conditions). You may not scrape, spider, use a robot, or use other automated means of any kind to access the Services.</li>
        <li>In any way use the Services to send altered, deceptive, or false source-identifying information (such as sending email communications falsely appearing as Yellow Alley); or interfere with, or disrupt, (or attempt to do so), the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the platforms or services, or in any other manner interfering with or creating an undue burden on the Services.</li>
        </ul>
        <h4>7. Miscellaneous Legal Terms</h4>
        These Terms are like any other contract, and they have boring but important legal terms that protect us from the countless things that could happen and that clarify the legal relationship between us and you.
        <h4>7.1 Binding Agreement</h4>
        You agree that by registering, accessing or using our Services, you are agreeing to enter into a legally binding contract with Yellow Alley. If you do not agree to these Terms, do not register, access, or otherwise use any of our Services.<br><br>
        Any version of these Term in a language other than English is provided for convenience and you understand and agree that the English language will control if there is any conflict.
        These Terms (including any agreements and policies linked from these Terms) constitute the entire agreement between you and us.<br><br>
        If any part of these Terms is found to be invalid or unenforceable by applicable law, then that provision will be deemed superseded by a valid, enforceable provision that most closely matches the intent of the original provision and the remainder of these Terms will continue in effect.<br><br>
        Even if we are delayed in exercising our rights or fail to exercise a right in one case, it doesn’t mean we waive our rights under these Terms, and we may decide to enforce them in the future. If we decide to waive any of our rights in a particular instance, it doesn’t mean we waive our rights generally or in the future.<br><br>
        The following sections shall survive the expiration or termination of these Terms: Sections 2 (Course Enrolment and Limited time Access), 5 (Using Yellow Alley at Your Own Risk), 6 (Yellow Alley’s Rights), 7 (Miscellaneous Legal Terms), and 8 (Dispute Resolution).
        <h4>7.2 Disclaimers</h4>
        It may happen that our platform is down, either for planned maintenance or because something goes down with the site. It may also happen that we encounter security issues. These are just examples. You accept that you will not have any recourse against us in any of these types of cases where things don’t work out right. In legal, more complete language, <strong>the Services and their content are provided on an “as is” and “as available” basis. We (and our affiliates, suppliers, partners, and agents) make no representations or warranties about the suitability, reliability, availability, timeliness, security, lack of errors, or accuracy of the Services or their content, and expressly disclaim any warranties or conditions (express or implied), including implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. We (and our affiliates, suppliers, partners, and agents) make no warranty that you will obtain specific results from use of the Services. Your use of the Services (including any content) is entirely at your own risk. Some jurisdictions don’t allow the exclusion of implied warranties, so some of the above exclusions may not apply to you.</strong><br><br>
        We may decide to cease making available certain features of the Services at any time and for any reason. Under no circumstances will Yellow Alley or its affiliates, suppliers, partners or agents be held liable for any damages due to such interruptions or lack of availability of such features.<br><br>
        We are not responsible for delay or failure of our performance of any of the Services caused by events beyond our reasonable control, like an act of war, hostility, or sabotage; natural disaster; electrical, internet, or telecommunication outage; or government restrictions.
        <h4>7.3 Limitation of Liability</h4>
        There are risks inherent into using our Services, for example, if you enrol in any course and you injure yourself. You fully accept these risks and you agree that you will have no recourse to seek damages against even if you suffer loss or damage from using our platform and Services. In legal, more complete language,<strong>to the extent permitted by law, we (and our group companies, suppliers, partners, and agents) will not be liable for any indirect, incidental, punitive, or consequential damages (including loss of data, revenue, profits, or business opportunities, or personal injury or death), whether arising in contract, warranty, tort, product liability, or otherwise, and even if we’ve been advised of the possibility of damages in advance. Our liability (and the liability of each of our group companies, suppliers, partners, and agents) to you or any third parties under any circumstance is limited and no amount will be paid. Some jurisdictions don’t allow the exclusion or limitation of liability for consequential or incidental damages, so some of the above may not apply to you.</strong>
        <h4>7.4 Indemnification</h4>
        If you behave in a way that gets us in legal trouble, we may exercise legal recourse against you. You agree to indemnify, defend (if we so request), and hold harmless Yellow Alley, our group companies, and their officers, directors, suppliers, partners, and agents from an against any third-party claims, demands, losses, damages, or expenses (including reasonable attorney fees) arising from (a) the content posted or submit, (b) your use of the Services (c) your violation of these Terms, or (d) your violation of any rights of a third party. Your indemnification obligation will survive the termination of these Terms and your use of the Services.
        <h4>7.5 Governing Law and Jurisdiction</h4>
        These Terms are governed by the laws of INDIA without reference to its choice or conflicts of law principles. Where the “Dispute Resolution” section below does not apply, you and we consent to the exclusive jurisdiction and venue of District and state courts in New Delhi, India.
        <h4>7.6 Legal Actions and Notices</h4>
        No action, regardless of form, arising out of or relating to this Agreement may be brought by either party more than six (6) months after the cause of action has accrued.<br><br>
        Any notice or other communication to be given here under will be in writing and given by registered or certified mail return receipt requested, or email (by us to the email associated with your account or by you to info@yellowalley.org).
        <h4>7.7 Relationship Between Us</h4>
        You and we agree that no joint venture, partnership, employment, contractor, or agency relationship exists between us.
        <h4>7.8 No Assignment</h4>
        You may not assign or transfer these Terms (or the rights and licenses granted under them). For example, if you registered an account as a student of a company, your account cannot be transferred to another student. We may assign these Terms (or the rights and licenses granted under them) to another company or person without restriction. Nothing in these Terms confers any right, benefit, or remedy on any third-party person or entity. You agree that your account is non-transferable and that all rights to your account and other rights under these Terms terminate upon your death.
        <h4>8. Dispute Resolution</h4>
        If there’s a dispute, our Support Team is happy to help resolve the issue. You may not bring any claim in any court or participate in a non-individual class action claim against us.
        Most disputes can be resolved by contacting our Support Team.
        <h4>8.1 Going to Arbitration</h4>
        If we can’t resolve our dispute amicably, you and Yellow Alley agree to resolve any claims related to these Terms (or our other legal terms) through final and binding arbitration, regardless of the type of claim or legal theory. No claim can be taken to court without arbitration.
        <h4> 8.2 No Class Actions</h4>
        We both agree that we can each only bring claims against the other on an individual basis. This means: (a) neither of us can bring a claim as a plaintiff or class member in a class action, consolidated action, or representative action; (b) an arbitrator can’t combine multiple people’s claims into a single case (or preside over any consolidated, class, or representative action); and (c) an arbitrator’s decision or award in one person’s case can only impact that user, not other users, and can’t be used to decide other users’ disputes. If a court decides that this “No class actions” clause isn’t enforceable or valid, then this “Dispute Resolution” section will be null and void, but the rest of the Terms will still apply.
        <h4>8.3 Changes</h4>
        Notwithstanding the “Updating these Terms” section below, if Yellow Alley changes this "Dispute Resolution" section after the date you last indicated acceptance to these Terms, you may reject any such change by providing Yellow Alley written notice of such rejection by email from the email address associated with your Account to: info@yellowalley.org, within 15 days of the date such change became effective, as indicated by the "last updated on" language above. To be effective, the notice must include your full name and clearly indicate your intent to reject changes to this "Dispute Resolution" section. By rejecting changes, you are agreeing that you will arbitrate any dispute between you and Yellow Alley in accordance with the provisions of this "Dispute Resolution" section as of the date you last indicated acceptance to these Terms.
        <h4>9. Updating These Terms</h4>
        From time to time, we may update these Terms to clarify our practices or to reflect new or different practices (such as when we add new features), and Yellow Alley reserves the right in its sole discretion to modify and/or make changes to these Terms at any time. If we make any material change, we will notify you using prominent means. Modifications will become effective on the day they are posted unless stated otherwise.<br><br>
        Your continued use of our Services after changes become effective shall mean that you accept those changes. Any revised Terms shall supersede all previous Terms.
        <h4>10. How to Contact Us</h4>
        The best way to get in touch with us is to contact our Support Team by mailing us at info@yellowalley.org. We’d love to hear your questions, concerns, and feedback about our Services.<br>
        Thanks for learning with us. Be Able!

    </div>
</body>
</html>
